<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#All-Cell-annotations" data-toc-modified-id="All-Cell-annotations-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>All Cell annotations</a></span></li><li><span><a href="#Parse-BALF-GEO-Series" data-toc-modified-id="Parse-BALF-GEO-Series-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Parse BALF GEO Series</a></span><ul class="toc-item"><li><span><a href="#Parse-CellRanger-HDF5-files" data-toc-modified-id="Parse-CellRanger-HDF5-files-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Parse CellRanger HDF5 files</a></span><ul class="toc-item"><li><span><a href="#File-Format" data-toc-modified-id="File-Format-2.1.1"><span class="toc-item-num">2.1.1&nbsp;&nbsp;</span>File Format</a></span></li></ul></li><li><span><a href="#Parse-CellRanger-3.0+-Feature-Barcode-Matricies" data-toc-modified-id="Parse-CellRanger-3.0+-Feature-Barcode-Matricies-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Parse CellRanger 3.0+ Feature-Barcode Matricies</a></span></li></ul></li><li><span><a href="#All-Samples" data-toc-modified-id="All-Samples-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>All Samples</a></span></li><li><span><a href="#Get-model-genes" data-toc-modified-id="Get-model-genes-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Get model genes</a></span></li><li><span><a href="#Model-genes-for-all-celltypes-per-patient" data-toc-modified-id="Model-genes-for-all-celltypes-per-patient-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Model genes for all celltypes per patient</a></span><ul class="toc-item"><li><span><a href="#Write-out-unnormalized-counts-of-model-genes" data-toc-modified-id="Write-out-unnormalized-counts-of-model-genes-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Write out unnormalized counts of model genes</a></span></li><li><span><a href="#Library-size-normalization" data-toc-modified-id="Library-size-normalization-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>Library size normalization</a></span></li><li><span><a href="#Write-out-library-normalized-counts-of-genes" data-toc-modified-id="Write-out-library-normalized-counts-of-genes-5.3"><span class="toc-item-num">5.3&nbsp;&nbsp;</span>Write out library normalized counts of genes</a></span></li><li><span><a href="#All-samples-and-cell-types" data-toc-modified-id="All-samples-and-cell-types-5.4"><span class="toc-item-num">5.4&nbsp;&nbsp;</span>All samples and cell types</a></span></li><li><span><a href="#Extract-samples-for-each-celltype" data-toc-modified-id="Extract-samples-for-each-celltype-5.5"><span class="toc-item-num">5.5&nbsp;&nbsp;</span>Extract samples for each celltype</a></span></li></ul></li><li><span><a href="#Healthy-control-4-(HC4)" data-toc-modified-id="Healthy-control-4-(HC4)-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Healthy control 4 (HC4)</a></span><ul class="toc-item"><li><span><a href="#Parse-Healthy-control-4-(HC4)-GEO-Sample" data-toc-modified-id="Parse-Healthy-control-4-(HC4)-GEO-Sample-6.1"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>Parse Healthy control 4 (HC4) GEO Sample</a></span></li></ul></li><li><span><a href="#Macrophage" data-toc-modified-id="Macrophage-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Macrophage</a></span><ul class="toc-item"><li><span><a href="#Epithelial-cells" data-toc-modified-id="Epithelial-cells-7.1"><span class="toc-item-num">7.1&nbsp;&nbsp;</span>Epithelial cells</a></span><ul class="toc-item"><li><span><a href="#Severe-COVID-19-patient-2-(S2)-Epithelial-cell-barcodes" data-toc-modified-id="Severe-COVID-19-patient-2-(S2)-Epithelial-cell-barcodes-7.1.1"><span class="toc-item-num">7.1.1&nbsp;&nbsp;</span>Severe COVID-19 patient 2 (S2) Epithelial cell barcodes</a></span></li><li><span><a href="#Healthy-control-4-(HC4)-Epithelial-cell-barcodes" data-toc-modified-id="Healthy-control-4-(HC4)-Epithelial-cell-barcodes-7.1.2"><span class="toc-item-num">7.1.2&nbsp;&nbsp;</span>Healthy control 4 (HC4) Epithelial cell barcodes</a></span></li></ul></li><li><span><a href="#Compare-Raw-HC4-barcodes-with-Metdata-HC4-barcodes" data-toc-modified-id="Compare-Raw-HC4-barcodes-with-Metdata-HC4-barcodes-7.2"><span class="toc-item-num">7.2&nbsp;&nbsp;</span>Compare Raw HC4 barcodes with Metdata HC4 barcodes</a></span></li></ul></li><li><span><a href="#Number-of-Epithelial-cells-in-H4" data-toc-modified-id="Number-of-Epithelial-cells-in-H4-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Number of Epithelial cells in H4</a></span><ul class="toc-item"><li><span><a href="#Write-out-Healthy-Control-4-epithelial-cells-to-csv" data-toc-modified-id="Write-out-Healthy-Control-4-epithelial-cells-to-csv-8.1"><span class="toc-item-num">8.1&nbsp;&nbsp;</span>Write out Healthy Control 4 epithelial cells to csv</a></span></li></ul></li><li><span><a href="#Severe-COVID-19-patient-2" data-toc-modified-id="Severe-COVID-19-patient-2-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>Severe COVID-19 patient 2</a></span><ul class="toc-item"><li><span><a href="#Parse-Severe-COVID-19-patient-2-(S2)-GEO-sample-file" data-toc-modified-id="Parse-Severe-COVID-19-patient-2-(S2)-GEO-sample-file-9.1"><span class="toc-item-num">9.1&nbsp;&nbsp;</span>Parse Severe COVID-19 patient 2 (S2) GEO sample file</a></span></li><li><span><a href="#Parse-S2-raw-HDF5-file" data-toc-modified-id="Parse-S2-raw-HDF5-file-9.2"><span class="toc-item-num">9.2&nbsp;&nbsp;</span>Parse S2 raw HDF5 file</a></span></li><li><span><a href="#Compare-Raw-S2-barcodes-with-S2-metadata-barcodes" data-toc-modified-id="Compare-Raw-S2-barcodes-with-S2-metadata-barcodes-9.3"><span class="toc-item-num">9.3&nbsp;&nbsp;</span>Compare Raw S2 barcodes with S2 metadata barcodes</a></span></li><li><span><a href="#Healthy-controls" data-toc-modified-id="Healthy-controls-9.4"><span class="toc-item-num">9.4&nbsp;&nbsp;</span>Healthy controls</a></span></li><li><span><a href="#Write-out-epithelial-samples-to-csv" data-toc-modified-id="Write-out-epithelial-samples-to-csv-9.5"><span class="toc-item-num">9.5&nbsp;&nbsp;</span>Write out epithelial samples to csv</a></span></li></ul></li></ul></div>


# All Cell annotations

Cell metadata annotations relable the suffix of barcodes [github issue #6](https://github.com/zhangzlab/covid_balf/issues/6)

In [10]:
!pwd

/Users/zuck016/Projects/Proposals/MARS/Pathogenesis/Covid-19-Causal-Reasoning/NeurIPS-determinants-of-viral-pathogenesis

In [2]:
import pandas as pd, os
import GEOparse
all_cells = pd.read_csv('data/all.cell.annotation.meta.txt',sep='\t')
all_cells['barcode'] = all_cells['ID'].str.split('_').str.get(0) + '_' + all_cells['sample_new']
all_cells.head()

,ID,sample,sample_new,group,disease,hasnCoV,cluster,celltype,barcode
0,AAACCTGAGACACTAA_1,C51,HC1,HC,N,N,3,Macrophages,AAACCTGAGACACTAA_HC1
1,AAACCTGAGGAGTACC_1,C51,HC1,HC,N,N,3,Macrophages,AAACCTGAGGAGTACC_HC1
2,AAACCTGAGGATATAC_1,C51,HC1,HC,N,N,3,Macrophages,AAACCTGAGGATATAC_HC1
3,AAACCTGAGGTCATCT_1,C51,HC1,HC,N,N,3,Macrophages,AAACCTGAGGTCATCT_HC1
4,AAACCTGCACGGATAG_1,C51,HC1,HC,N,N,5,Macrophages,AAACCTGCACGGATAG_HC1

In [3]:
all_barcodes = set(all_cells['barcode'].values.tolist())

len(all_barcodes)

65813

In [4]:
celltypes = set(all_cells['celltype'].values)
celltypes

{'B',
 'Epithelial',
 'Macrophages',
 'Mast',
 'NK',
 'Neutrophil',
 'Plasma',
 'T',
 'mDC',
 'pDC'}

In [5]:
cell_counts = all_cells.groupby(['celltype', 'group']).count()
cell_counts

                      ID  sample  sample_new  disease  hasnCoV  cluster  \
celltype    group
B           HC        51      51          51       51       51       51
            M         67      67          67       67       67       67
            S        102     102         102      102      102      102
Epithelial  HC      1442    1442        1442     1442     1442     1442
            M        215     215         215      215      215      215
            S       1874    1874        1874     1874     1874     1874
Macrophages HC     18539   18539       18539    18539    18539    18539
            M       4353    4353        4353     4353     4353     4353
            S      26525   26525       26525    26525    26525    26525
Mast        HC        25      25          25       25       25       25
            M          6       6           6        6        6        6
            S         39      39          39       39       39       39
NK          HC        97      97          97       97       97       97
            M        298     298         298      298      298      298
            S        686     686         686      686      686      686
Neutrophil  M          4       4           4        4        4        4
            S       1603    1603        1603     1603     1603     1603
Plasma      HC         3       3           3        3        3        3
            M         14      14          14       14       14       14
            S       1024    1024        1024     1024     1024     1024
T           HC      1225    1225        1225     1225     1225     1225
            M       2135    2135        2135     2135     2135     2135
            S       4356    4356        4356     4356     4356     4356
mDC         HC       485     485         485      485      485      485
            M        159     159         159      159      159      159
            S        334     334         334      334      334      334
pDC         HC        16      16          16       16       16       16
            M         60      60          60       60       60       60
            S         76      76          76       76       76       76

                   barcode
celltype    group
B           HC          51
            M           67
            S          102
Epithelial  HC        1442
            M          215
            S         1874
Macrophages HC       18539
            M         4353
            S        26525
Mast        HC          25
            M            6
            S           39
NK          HC          97
            M          298
            S          686
Neutrophil  M            4
            S         1603
Plasma      HC           3
            M           14
            S         1024
T           HC        1225
            M         2135
            S         4356
mDC         HC         485
            M          159
            S          334
pDC         HC          16
            M           60
            S           76

In [6]:
patients = sorted(set(all_cells['sample_new'].values))
patients

['HC1',
 'HC2',
 'HC3',
 'HC4',
 'M1',
 'M2',
 'M3',
 'S1',
 'S2',
 'S3',
 'S4',
 'S5',
 'S6']

In [7]:
patient_to_sample = dict(all_cells.groupby(['sample_new', 'sample']).count().index.tolist())
patient_to_sample

{'HC1': 'C51',
 'HC2': 'C52',
 'HC3': 'C100',
 'HC4': 'GSM3660650',
 'M1': 'C141',
 'M2': 'C142',
 'M3': 'C144',
 'S1': 'C145',
 'S2': 'C143',
 'S3': 'C146',
 'S4': 'C148',
 'S5': 'C149',
 'S6': 'C152'}

In [8]:
sample_to_patient = dict(all_cells.groupby(['sample','sample_new']).count().index.tolist())
sample_to_patient

{'C100': 'HC3',
 'C141': 'M1',
 'C142': 'M2',
 'C143': 'S2',
 'C144': 'M3',
 'C145': 'S1',
 'C146': 'S3',
 'C148': 'S4',
 'C149': 'S5',
 'C152': 'S6',
 'C51': 'HC1',
 'C52': 'HC2',
 'GSM3660650': 'HC4'}

In [9]:
def get_celltype_barcodes_from_patient( patient,  celltype, all_cells):
    return set(all_cells[(all_cells['sample_new'] == patient) &
                                               (all_cells['celltype'] == celltype)]['barcode']
                                    .values.tolist())
def extract_celltype_from_patient(patient, raw, celltype, all_cells ):
    old_barcodes = raw[patient].columns
    raw[patient].columns = [bc.split('-')[0] for bc in old_barcodes]
    celltype_barcodes = get_celltype_barcodes_from_patient( patient, raw, celltype, all_cells)
    return raw[patient][sorted(celltype_barcodes)]

def get_metadata_barcodes_from_patient(patient, raw, all_cells):
    return set(all_cells[all_cells['sample_new'] == patient]['ID']
                                    .str.split('_').str.get(0)
                                    .values.tolist())

# Parse BALF GEO Series

In [10]:
import os 
import GEOparse
mars_dir = '../../MARS-Pathogenesis/'
balf_dir = os.path.join(mars_dir,'Coronavirus/SARS-CoV-2/COVID-BALF/')
balf_files = [f for f in os.listdir(balf_dir) if '.h5' in f]
balf_files

['GSM4339769_C141_filtered_feature_bc_matrix.h5',
 'GSM4339770_C142_filtered_feature_bc_matrix.h5',
 'GSM4339771_C143_filtered_feature_bc_matrix.h5',
 'GSM4339772_C144_filtered_feature_bc_matrix.h5',
 'GSM4339773_C145_filtered_feature_bc_matrix.h5',
 'GSM4339774_C146_filtered_feature_bc_matrix.h5',
 'GSM4475048_C51_filtered_feature_bc_matrix.h5',
 'GSM4475049_C52_filtered_feature_bc_matrix.h5',
 'GSM4475050_C100_filtered_feature_bc_matrix.h5',
 'GSM4475051_C148_filtered_feature_bc_matrix.h5',
 'GSM4475052_C149_filtered_feature_bc_matrix.h5',
 'GSM4475053_C152_filtered_feature_bc_matrix.h5']

In [19]:

gse = GEOparse.get_GEO(geo="GSE145926", destdir=balf_dir)

for gsm_name, gsm in gse.gsms.items():
    print("Name: ", gsm_name)
    print("Metadata:",)
    for key, value in gsm.metadata.items():
        print(" - %s : %s" % (key, ", ".join(value)))
    print ("Table data:",)
    print (gsm.table.head())
    break

13-Jun-2020 15:24:42 DEBUG utils - Directory ../../MARS-Pathogenesis/Coronavirus/SARS-CoV-2/COVID-BALF/ already exists. Skipping.
13-Jun-2020 15:24:42 INFO GEOparse - File already exist: using local version.
13-Jun-2020 15:24:42 INFO GEOparse - Parsing ../../MARS-Pathogenesis/Coronavirus/SARS-CoV-2/COVID-BALF/GSE145926_family.soft.gz:
13-Jun-2020 15:24:42 DEBUG GEOparse - DATABASE: GeoMiame
13-Jun-2020 15:24:42 DEBUG GEOparse - SERIES: GSE145926
13-Jun-2020 15:24:42 DEBUG GEOparse - PLATFORM: GPL23227
13-Jun-2020 15:24:42 DEBUG GEOparse - SAMPLE: GSM4339769
13-Jun-2020 15:24:42 DEBUG GEOparse - SAMPLE: GSM4339770
13-Jun-2020 15:24:42 DEBUG GEOparse - SAMPLE: GSM4339771
13-Jun-2020 15:24:42 DEBUG GEOparse - SAMPLE: GSM4339772
13-Jun-2020 15:24:43 DEBUG GEOparse - SAMPLE: GSM4339773
13-Jun-2020 15:24:43 DEBUG GEOparse - SAMPLE: GSM4339774
13-Jun-2020 15:24:43 DEBUG GEOparse - SAMPLE: GSM4385990
13-Jun-2020 15:24:43 DEBUG GEOparse - SAMPLE: GSM4385991
13-Jun-2020 15:24:43 DEBUG GEOparse - SAMPLE: GSM4385992
13-Jun-2020 15:24:43 DEBUG GEOparse - SAMPLE: GSM4385993
13-Jun-2020 15:24:43 DEBUG GEOparse - SAMPLE: GSM4385994
13-Jun-2020 15:24:43 DEBUG GEOparse - SAMPLE: GSM4385995
13-Jun-2020 15:24:43 DEBUG GEOparse - SAMPLE: GSM4475048
13-Jun-2020 15:24:43 DEBUG GEOparse - SAMPLE: GSM4475049
13-Jun-2020 15:24:43 DEBUG GEOparse - SAMPLE: GSM4475050
13-Jun-2020 15:24:43 DEBUG GEOparse - SAMPLE: GSM4475051
13-Jun-2020 15:24:43 DEBUG GEOparse - SAMPLE: GSM4475052
13-Jun-2020 15:24:43 DEBUG GEOparse - SAMPLE: GSM4475053
13-Jun-2020 15:24:43 DEBUG GEOparse - SAMPLE: GSM4475054
13-Jun-2020 15:24:43 DEBUG GEOparse - SAMPLE: GSM4475055
13-Jun-2020 15:24:43 DEBUG GEOparse - SAMPLE: GSM4475056

Name:  GSM4339769
Metadata:
 - title : BALF, C141 (scRNA-seq)
 - geo_accession : GSM4339769
 - status : Public on Apr 22 2020
 - submission_date : Feb 25 2020
 - last_update_date : Apr 22 2020
 - type : SRA
 - channel_count : 1
 - source_name_ch1 : BALF
 - organism_ch1 : Homo sapiens
 - taxid_ch1 : 9606
 - characteristics_ch1 : disease state: Coronavirus infected disease-19 (COVID-19), patient group: mild, tissue: lung, sample type: BALF, cell subsets: Total cell
 - molecule_ch1 : polyA RNA
 - extract_protocol_ch1 : Total 11 µl of single cell suspension and 40 µl barcoded Gel Beads were loaded to Chromium Chip A to generate single-cell gel bead-in-emulsion (GEM). The poly-adenylated transcripts were reverse-transcribed later. The single-cell capturing and downstream library constructions were performed using the Chromium Single Cell 5’ library preparation kit according to the manufacturer’s protocol (10x Genomics). Full-length cDNA along with cell-barcode identifiers were PCR-amplified and sequencing libraries were prepared and normalized to 3 nM.
 - description : Single-cell RNAseq data
 - data_processing : The Cell Ranger Software Suite (Version 3.1.0) was used to perform sample de-multiplexing, barcode processing and single-cell 5’ UMI counting with human GRCh38 as the reference genome. Specifically, splicing-aware aligner STAR was used in FASTQs alignment. Cell barcodes were then determined based on distribution of UMI count automatically. Finally, gene-barcode matrix of all 6 donors and 8 previously reported healthy control was integrated with Seurat v3 to remove batch effect across different donors. Following criteria were then applied to each cell, i.e., gene number between 200 and 6000, UMI count above 1000 and mitochondrial gene percentage below 0.1., The filtered gene-barcode matrix was normalized with LogNormalize methods in Seurat and analyzed by principal component analysis (PCA) using the top 2, 000 most variable genes. Then Uniform Manifold Approximation and Projection (UMAP) was performed on the top 50 principal components for visualizing the cells. Meanwhile, graph-based clustering was performed on the PCA-reduced data for clustering analysis with Seurat v3., MAST in Seurat v3 was used to perform differential analysis. For each cluster, differentially-expressed genes (DEGs) were generated relative to all of the other cells., The TCR sequences for each single T cell were assembled by Cell Ranger vdj pipeline (v3.1.0), leading to the identification of CDR3 sequence and the rearranged TCR gene. Cells with both TCR alpha and beta chains were kept and cells with only one TCR chain were discarded., Genome_build: GRCh38 + COVID(MN908947), Supplementary_files_format_and_content: h5, raw count matrix generated by Cell Ranger count; csv, tcr contig annotations generated by Cell Ranger vdj
 - platform_id : GPL23227
 - contact_name : Zheng,,Zhang
 - contact_institute : Shenzhen 3rd People's Hospital
 - contact_address : No. 29, Bulan Road
 - contact_city : Shenzhen
 - contact_state : Guangdong
 - contact_zip/postal_code : 454171
 - contact_country : China
 - instrument_model : BGISEQ-500
 - library_selection : cDNA
 - library_source : transcriptomic
 - library_strategy : RNA-Seq
 - relation : BioSample: https://www.ncbi.nlm.nih.gov/biosample/SAMN14207961, SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX7802546
 - supplementary_file_1 : ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM4339nnn/GSM4339769/suppl/GSM4339769_C141_filtered_feature_bc_matrix.h5
 - series_id : GSE145926
 - data_row_count : 0
Table data:
Empty DataFrame
Columns: []
Index: []

## Parse CellRanger HDF5 files

Convert [PyTables functions as recommended by 10xGenomics](https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/advanced/h5_matrices) into a dataframe

### File Format

The top level of the file contains a single HDF5 group, called matrix, and metadata stored as HDF5 attributes. Within the matrix group are datasets containing the dimensions of the matrix, the matrix entries, as well as the features and cell-barcodes associated with the matrix rows and columns, respectively.

|Column	|Type	|Description|
|-------|-------|----------|
|barcodes|	`string`|	Barcode sequences and their corresponding GEM wells (e.g. AAACGGGCAGCTCGAC-1)
data|	`uint32`|	Nonzero UMI counts in column-major order
indices|	`uint32`|	Zero-based row index of corresponding element in data
indptr|	`uint32`	|Zero-based index into data / indices of the start of each column, i.e., the data corresponding to each barcode sequence
shape	|`uint64`	|Tuple of (# rows, # columns) indicating the matrix dimensions

In [11]:
import collections
import scipy.sparse as sp_sparse
import tables
 
CountMatrix = collections.namedtuple('CountMatrix', ['feature_ref', 'barcodes', 'matrix'])

def b2a(fg, attr):
    return [gene.decode("utf-8")  for gene in getattr(fg, attr).read().tolist()]
def get_matrix_from_h5(filename):
    with tables.open_file(filename, 'r') as f:
        mat_group = f.get_node(f.root, 'matrix')
        barcodes = [barcode.decode('utf-8') for barcode in f.get_node(mat_group, 'barcodes').read().tolist()]
        data = getattr(mat_group, 'data').read()
        indices = getattr(mat_group, 'indices').read()
        indptr = getattr(mat_group, 'indptr').read()
        shape = getattr(mat_group, 'shape').read()
        matrix = sp_sparse.csc_matrix((data, indices, indptr), shape=shape)
         
        feature_ref = {}
        feature_group = f.get_node(mat_group, 'features')
        feature_ids = b2a(feature_group, 'id')
        feature_names = b2a(feature_group, 'name')
        feature_types = b2a(feature_group, 'feature_type')
        feature_ref['id'] = feature_ids
        feature_ref['name'] = feature_names
        feature_ref['feature_type'] = feature_types
        tag_keys = b2a(feature_group, '_all_tag_keys')
        for key in tag_keys:
            if type(key) is not str:
                key = key.decode("utf-8") 
                feature_ref[key] = b2a(feature_group, key)
            else:
                print(type(key), key)
        cmx = CountMatrix(feature_ref, barcodes, matrix)
        gene_names= cmx.feature_ref['name']
        barcodes =  cmx.barcodes
        mat = cmx.matrix
        rows,cols = mat.shape
        if len(gene_names) == rows and len(barcodes) == cols:  
            return pd.DataFrame.sparse.from_spmatrix(data=mat, columns=barcodes, index=gene_names)
        elif len(gene_names) == cols and len(barcodes) == rows:  
            return pd.DataFrame.sparse.from_spmatrix(data=mat, index=barcodes, columns=gene_names )
        else:
            print("Rows, cols =", rows, cols, "genes, barcodes=",len(gene_names), len(barcodes))

## Parse CellRanger 3.0+ Feature-Barcode Matricies

[CellRanger Format description according to 10xgenomics](https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/output/matrices):

Each matrix is stored in the [Market Exchange Format (MEX)](https://math.nist.gov/MatrixMarket/formats.html) for sparse matrices. It also contains gzipped TSV files with feature and barcode sequences corresponding to row and column indices respectively. For example, the matrices output may look like
```
$ cd /home/jdoe/runs/sample345/outs
$ tree filtered_feature_bc_matrix
filtered_feature_bc_matrix
├── barcodes.tsv.gz
├── features.tsv.gz
└── matrix.mtx.gz
0 directories, 3 files
```

In [12]:
import gzip, csv
import os
import scipy.io
 

def parse_mtx(barcodes_path, features_path, mtx_path):
    """Return a dataframe with barcodes and features and matrix data"""
    mat = scipy.io.mmread(mtx_path)
    rows, cols = mat.shape
    features = pd.read_csv(features_path,delimiter='\t',compression='gzip',header=None,
                           names=['feature_id','gene_name', 'feature_type'])
    
    barcodes = pd.read_csv(barcodes_path, delimiter="\t", 
                           compression='gzip', 
                           header=None,
                           names=['barcode']
                           )
    if len(features.index) == rows and len(barcodes.index) == cols:  
        return pd.DataFrame.sparse.from_spmatrix(data=mat, columns=barcodes['barcode'], index=features['gene_name'])
    elif len(features.index) == cols and len(barcodes.index) == rows:  
        return pd.DataFrame.sparse.from_spmatrix(data=mat, index=barcodes['barcode'], columns=features['gene_name'] )
    else:
        print("Rows, cols =", rows, cols, "genes, barcodes=",len(gene_names), len(barcodes))

# All Samples

In [13]:
balf_files, sample_to_patient

(['GSM4339769_C141_filtered_feature_bc_matrix.h5',
  'GSM4339770_C142_filtered_feature_bc_matrix.h5',
  'GSM4339771_C143_filtered_feature_bc_matrix.h5',
  'GSM4339772_C144_filtered_feature_bc_matrix.h5',
  'GSM4339773_C145_filtered_feature_bc_matrix.h5',
  'GSM4339774_C146_filtered_feature_bc_matrix.h5',
  'GSM4475048_C51_filtered_feature_bc_matrix.h5',
  'GSM4475049_C52_filtered_feature_bc_matrix.h5',
  'GSM4475050_C100_filtered_feature_bc_matrix.h5',
  'GSM4475051_C148_filtered_feature_bc_matrix.h5',
  'GSM4475052_C149_filtered_feature_bc_matrix.h5',
  'GSM4475053_C152_filtered_feature_bc_matrix.h5'],
 {'C100': 'HC3',
  'C141': 'M1',
  'C142': 'M2',
  'C143': 'S2',
  'C144': 'M3',
  'C145': 'S1',
  'C146': 'S3',
  'C148': 'S4',
  'C149': 'S5',
  'C152': 'S6',
  'C51': 'HC1',
  'C52': 'HC2',
  'GSM3660650': 'HC4'})

In [14]:
def get_raw_barcodes_for_patient(raw_patient):
    return set([raw_barcode.split('-')[0] for raw_barcode in raw_patient.columns])
def get_all_samples(balf_files, sample_to_patient ): 
    raw = {}
    geo = {}
    raw_barcodes = {}
    for gsm_file in balf_files:
        gsm_id, sample = gsm_file.split('_')[0:2]
        patient = sample_to_patient[sample]
        geo[patient] = GEOparse.get_GEO(geo=gsm_id, destdir=balf_dir)
        if patient == 'HC4':
            raw[patient] = parse_mtx(os.path.join(balf_dir,'GSM3660650_SC249NORbal_fresh_barcodes.tsv.gz'),
                                     os.path.join(balf_dir,'GSM3660650_SC249NORbal_fresh_genes.tsv.gz'),
                                     os.path.join(balf_dir,'GSM3660650_SC249NORbal_fresh_matrix.mtx.gz'))
        else:
            raw[patient] = get_matrix_from_h5(os.path.join(balf_dir,gsm_file))
        raw[patient].columns = [bc.split('-')[0] + '_' + patient for bc in raw[patient].columns]
        raw_barcodes[patient] = raw[patient].columns
    return geo, raw, raw_barcodes

In [15]:
geo, raw, raw_barcodes = get_all_samples( ['GSM3660650_GSM3660650'] +balf_files, sample_to_patient )

14-Jun-2020 13:12:18 DEBUG utils - Directory ../../MARS-Pathogenesis/Coronavirus/SARS-CoV-2/COVID-BALF/ already exists. Skipping.
14-Jun-2020 13:12:18 INFO GEOparse - File already exist: using local version.
14-Jun-2020 13:12:18 INFO GEOparse - Parsing ../../MARS-Pathogenesis/Coronavirus/SARS-CoV-2/COVID-BALF/GSM3660650.txt:
14-Jun-2020 13:17:55 DEBUG utils - Directory ../../MARS-Pathogenesis/Coronavirus/SARS-CoV-2/COVID-BALF/ already exists. Skipping.
14-Jun-2020 13:17:55 INFO GEOparse - File already exist: using local version.
14-Jun-2020 13:17:55 INFO GEOparse - Parsing ../../MARS-Pathogenesis/Coronavirus/SARS-CoV-2/COVID-BALF/GSM4339769.txt:

<class 'str'> genome

14-Jun-2020 13:17:59 DEBUG utils - Directory ../../MARS-Pathogenesis/Coronavirus/SARS-CoV-2/COVID-BALF/ already exists. Skipping.
14-Jun-2020 13:17:59 INFO GEOparse - File already exist: using local version.
14-Jun-2020 13:17:59 INFO GEOparse - Parsing ../../MARS-Pathogenesis/Coronavirus/SARS-CoV-2/COVID-BALF/GSM4339770.txt:

<class 'str'> genome

14-Jun-2020 13:18:05 DEBUG utils - Directory ../../MARS-Pathogenesis/Coronavirus/SARS-CoV-2/COVID-BALF/ already exists. Skipping.
14-Jun-2020 13:18:05 INFO GEOparse - File already exist: using local version.
14-Jun-2020 13:18:05 INFO GEOparse - Parsing ../../MARS-Pathogenesis/Coronavirus/SARS-CoV-2/COVID-BALF/GSM4339771.txt:

<class 'str'> genome

14-Jun-2020 13:18:19 DEBUG utils - Directory ../../MARS-Pathogenesis/Coronavirus/SARS-CoV-2/COVID-BALF/ already exists. Skipping.
14-Jun-2020 13:18:19 INFO GEOparse - File already exist: using local version.
14-Jun-2020 13:18:19 INFO GEOparse - Parsing ../../MARS-Pathogenesis/Coronavirus/SARS-CoV-2/COVID-BALF/GSM4339772.txt:

<class 'str'> genome

14-Jun-2020 13:18:21 DEBUG utils - Directory ../../MARS-Pathogenesis/Coronavirus/SARS-CoV-2/COVID-BALF/ already exists. Skipping.
14-Jun-2020 13:18:21 INFO GEOparse - File already exist: using local version.
14-Jun-2020 13:18:21 INFO GEOparse - Parsing ../../MARS-Pathogenesis/Coronavirus/SARS-CoV-2/COVID-BALF/GSM4339773.txt:

<class 'str'> genome

14-Jun-2020 13:18:30 DEBUG utils - Directory ../../MARS-Pathogenesis/Coronavirus/SARS-CoV-2/COVID-BALF/ already exists. Skipping.
14-Jun-2020 13:18:30 INFO GEOparse - File already exist: using local version.
14-Jun-2020 13:18:30 INFO GEOparse - Parsing ../../MARS-Pathogenesis/Coronavirus/SARS-CoV-2/COVID-BALF/GSM4339774.txt:

<class 'str'> genome

14-Jun-2020 13:18:33 DEBUG utils - Directory ../../MARS-Pathogenesis/Coronavirus/SARS-CoV-2/COVID-BALF/ already exists. Skipping.
14-Jun-2020 13:18:33 INFO GEOparse - File already exist: using local version.
14-Jun-2020 13:18:33 INFO GEOparse - Parsing ../../MARS-Pathogenesis/Coronavirus/SARS-CoV-2/COVID-BALF/GSM4475048.txt:

<class 'str'> genome

14-Jun-2020 13:18:39 DEBUG utils - Directory ../../MARS-Pathogenesis/Coronavirus/SARS-CoV-2/COVID-BALF/ already exists. Skipping.
14-Jun-2020 13:18:39 INFO GEOparse - File already exist: using local version.
14-Jun-2020 13:18:39 INFO GEOparse - Parsing ../../MARS-Pathogenesis/Coronavirus/SARS-CoV-2/COVID-BALF/GSM4475049.txt:

<class 'str'> genome

14-Jun-2020 13:18:45 DEBUG utils - Directory ../../MARS-Pathogenesis/Coronavirus/SARS-CoV-2/COVID-BALF/ already exists. Skipping.
14-Jun-2020 13:18:45 INFO GEOparse - File already exist: using local version.
14-Jun-2020 13:18:45 INFO GEOparse - Parsing ../../MARS-Pathogenesis/Coronavirus/SARS-CoV-2/COVID-BALF/GSM4475050.txt:

<class 'str'> genome

14-Jun-2020 13:18:50 DEBUG utils - Directory ../../MARS-Pathogenesis/Coronavirus/SARS-CoV-2/COVID-BALF/ already exists. Skipping.
14-Jun-2020 13:18:50 INFO GEOparse - File already exist: using local version.
14-Jun-2020 13:18:50 INFO GEOparse - Parsing ../../MARS-Pathogenesis/Coronavirus/SARS-CoV-2/COVID-BALF/GSM4475051.txt:

<class 'str'> genome

14-Jun-2020 13:18:53 DEBUG utils - Directory ../../MARS-Pathogenesis/Coronavirus/SARS-CoV-2/COVID-BALF/ already exists. Skipping.
14-Jun-2020 13:18:53 INFO GEOparse - File already exist: using local version.
14-Jun-2020 13:18:53 INFO GEOparse - Parsing ../../MARS-Pathogenesis/Coronavirus/SARS-CoV-2/COVID-BALF/GSM4475052.txt:

<class 'str'> genome

14-Jun-2020 13:18:54 DEBUG utils - Directory ../../MARS-Pathogenesis/Coronavirus/SARS-CoV-2/COVID-BALF/ already exists. Skipping.
14-Jun-2020 13:18:54 INFO GEOparse - File already exist: using local version.
14-Jun-2020 13:18:54 INFO GEOparse - Parsing ../../MARS-Pathogenesis/Coronavirus/SARS-CoV-2/COVID-BALF/GSM4475053.txt:

<class 'str'> genome

# Get model genes

In [16]:
import pybel, os
il6_dir = '../NeurIPS-determinants-of-viral-pathogenesis/BEL'
il6_amp_file = 'COVID-19-a-new-virus-but-an-old-cytokine-release-syndrome.bel.nodelink.json'
il6_amp = pybel.from_nodelink_file(os.path.join(il6_dir, il6_amp_file))
il6_amp.summarize()

Temporary Network v_akJ3f4e--_
Number of Nodes: 16
Number of Edges: 21
Number of Citations: 1
Number of Authors: 0
Network Density: 8.75E-02
Number of Components: 1
Number of Warnings: 0

In [61]:
def get_model_genes( model ):
    model_genes = []
    for node in il6_amp.nodes:
        if  not isinstance(node, pybel.dsl.ComplexAbundance):
            if node.namespace == 'HGNC':
                model_genes.append(node.name)
        else:
            print('\n'.join([m.name for m in node.members]))
    return model_genes

model_genes = get_model_genes( il6_amp )+ ['TNF', "EGFR", "NFKB1", "FCN1"]
model_genes

IL6
STAT3

['IL6',
 'STAT3',
 'ACE2',
 'ADAM17',
 'AGTR1',
 'EGF',
 'IL6R',
 'TNF',
 'EGFR',
 'NFKB1',
 'FCN1']

# Model genes for all celltypes per patient

In [84]:
patient='HC4'

In [62]:
all_cells[(all_cells['sample_new'] == patient)& (all_cells['celltype'] == celltype)]

,ID,sample,sample_new,group,disease,hasnCoV,cluster,celltype,barcode
62920,AAACCTGGTCAGTGGA_13,C152,S6,S,Y,N,6,T,AAACCTGGTCAGTGGA_S6
62924,AAACGGGGTTACCAGT_13,C152,S6,S,Y,N,9,T,AAACGGGGTTACCAGT_S6
62934,AAAGCAAGTGATAAGT_13,C152,S6,S,Y,N,9,T,AAAGCAAGTGATAAGT_S6
62935,AAAGCAAGTTTCGCTC_13,C152,S6,S,Y,N,14,T,AAAGCAAGTTTCGCTC_S6
62946,AAATGCCTCCGCATCT_13,C152,S6,S,Y,N,6,T,AAATGCCTCCGCATCT_S6
...,...,...,...,...,...,...,...,...,...
65791,TTTCCTCCAGGTCTCG_13,C152,S6,S,Y,N,14,T,TTTCCTCCAGGTCTCG_S6
65798,TTTGCGCTCTAACCGA_13,C152,S6,S,Y,N,9,T,TTTGCGCTCTAACCGA_S6
65799,TTTGCGCTCTGCTTGC_13,C152,S6,S,Y,N,14,T,TTTGCGCTCTGCTTGC_S6
65804,TTTGGTTCACTATCTT_13,C152,S6,S,Y,N,14,T,TTTGGTTCACTATCTT_S6
65809,TTTGTCAAGAAACGCC_13,C152,S6,S,Y,N,14,T,TTTGTCAAGAAACGCC_S6

## Write out unnormalized counts of model genes

In [63]:
for patient in patients:
    for celltype in celltypes:
        patient_celltype_barcodes= get_celltype_barcodes_from_patient( patient,  celltype, all_cells)
        patient_celltype_genes = raw[patient].loc[model_genes,patient_celltype_barcodes].T
        celltype_dir = os.path.join(balf_dir, celltype )

        if not os.path.exists(celltype_dir):
            os.mkdir(celltype_dir)
        patient_celltype_genes.to_csv(
            os.path.join(celltype_dir,
                         '{}_{}_model_genes.csv'.format(patient, celltype)))

## Library size normalization

Library size normalization is the simplest strategy for performing scaling normalization. We define the library size as the total sum of counts across all genes for each cell, the expected value of which is assumed to scale with any cell-specific biases. The “library size factor” for each cell is then directly proportional to its library size where the proportionality constant is defined such that the mean size factor across all cells is equal to 1. This definition ensures that the normalized expression values are on the same scale as the original counts, which is useful for interpretation - especially when dealing with transformed data

In [64]:
def library_size_factors( df, celltypes, patients ):
    library_size = {}
    library_sum = 0
    for patient in patients:
        for celltype in celltypes:
            patient_celltype_barcodes= get_celltype_barcodes_from_patient( patient,  celltype, all_cells)
            library_size[patient,celltype] = raw[patient][patient_celltype_barcodes].sum(axis=1)
            library_sum += library_size[patient,celltype].sum()
    library_size_factor = {}
    for patient in patients:
        for celltype in celltypes:
            library_size_factor[patient,celltype] = library_size[patient,celltype]/library_sum
    return library_size_factor

In [65]:
lsf = library_size_factors( raw, celltypes, patients )

In [66]:
def log_norm_counts( df, size_factors, pseudocounts=1, base=2):
    if base==2:
        return np.log2(df + pseudocounts).subtract(np.log2(size_factors + pseudocounts), axis='index')
    elif base:
        return np.log(df + pseudocounts).subtract(np.log(size_factors + pseudocounts) -np.log(base), axis='index')
    else:
        return np.log(df + pseudocounts).subtract(np.log(size_factors + pseudocounts), axis='index')

In [67]:
lsf[patient, celltype][model_genes]

IL6       0.000000e+00
STAT3     1.611377e-06
ACE2      0.000000e+00
ADAM17    8.340733e-07
AGTR1     0.000000e+00
EGF       0.000000e+00
IL6R      5.895283e-08
TNF       5.676939e-08
EGFR      0.000000e+00
NFKB1     1.423602e-06
FCN1      2.620126e-08
dtype: float64

## Write out library normalized counts of genes

In [68]:
import numpy as np 
library_normalized_patient_celltype_genes = {}
for patient in patients:
    for celltype in celltypes:
        patient_celltype_barcodes= get_celltype_barcodes_from_patient( patient,  celltype, all_cells)
        library_normalized_patient_celltype_genes[patient, celltype] = log_norm_counts(
            raw[patient].loc[model_genes,patient_celltype_barcodes],
            lsf[patient,celltype][model_genes])
        celltype_dir = os.path.join(balf_dir, celltype )

        if not os.path.exists(celltype_dir):
            os.mkdir(celltype_dir)
        library_normalized_patient_celltype_genes[patient,celltype].T.to_csv(
            os.path.join(celltype_dir,
                         'log_norm_count_{}_{}_model_genes.csv'.format(patient, celltype)))

In [71]:
library_normalized_patient_celltype_genes['S6','Epithelial']

,ATTGGACCAGGGATTG_S6,CATCCACGTCATGCAT_S6,ACCTTTAAGAACAATC_S6,CCTTTCTGTAGGCATG_S6,TATTACCCAAAGTGCG_S6,AGCAGCCGTCGAAAGC_S6,ATAGACCAGGAGTTGC_S6,GATCGTAGTTCCCGAG_S6,GGACATTTCATCTGTT_S6,ATTCTACAGGATGGTC_S6,...,TGCTACCAGTGGGTTG_S6,GAACGGAGTGCGATAG_S6,AGTGGGATCCACGCAG_S6,ACTGTCCCAGATAATG_S6,GACTACACACTCGACG_S6,GTACTCCGTCGTGGCT_S6,GGACGTCTCAGAGACG_S6,TATGCCCTCACAAACC_S6,AGGCCACCATTAGGCT_S6,TAGCCGGGTATAGGTA_S6
IL6,-6.300071e-09,-6.300071e-09,1.584962e+00,-6.300071e-09,-6.300071e-09,-6.300071e-09,-6.300071e-09,-6.300071e-09,-6.300071e-09,-6.300071e-09,...,-6.300071e-09,-6.300071e-09,-6.300071e-09,-6.300071e-09,-6.300071e-09,-6.300071e-09,-6.300071e-09,-6.300071e-09,-6.300071e-09,-6.300071e-09
STAT3,-1.146612e-06,-1.146612e-06,1.584961e+00,1.584961e+00,1.584961e+00,1.584961e+00,-1.146612e-06,-1.146612e-06,1.584961e+00,1.584961e+00,...,2.807354e+00,-1.146612e-06,9.999989e-01,-1.146612e-06,9.999989e-01,-1.146612e-06,9.999989e-01,-1.146612e-06,-1.146612e-06,9.999989e-01
ACE2,-7.560085e-08,-7.560085e-08,-7.560085e-08,-7.560085e-08,-7.560085e-08,-7.560085e-08,-7.560085e-08,-7.560085e-08,-7.560085e-08,-7.560085e-08,...,-7.560085e-08,-7.560085e-08,-7.560085e-08,-7.560085e-08,-7.560085e-08,-7.560085e-08,-7.560085e-08,-7.560085e-08,-7.560085e-08,-7.560085e-08
ADAM17,9.999991e-01,2.321927e+00,-8.505093e-07,-8.505093e-07,-8.505093e-07,9.999991e-01,-8.505093e-07,-8.505093e-07,-8.505093e-07,3.700439e+00,...,-8.505093e-07,-8.505093e-07,-8.505093e-07,1.584962e+00,9.999991e-01,-8.505093e-07,-8.505093e-07,-8.505093e-07,-8.505093e-07,-8.505093e-07
AGTR1,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
EGF,-1.575018e-08,-1.575018e-08,-1.575018e-08,-1.575018e-08,-1.575018e-08,-1.575018e-08,-1.575018e-08,-1.575018e-08,-1.575018e-08,-1.575018e-08,...,-1.575018e-08,-1.575018e-08,-1.575018e-08,-1.575018e-08,-1.575018e-08,-1.575018e-08,-1.575018e-08,-1.575018e-08,-1.575018e-08,-1.575018e-08
IL6R,-3.969044e-07,-3.969044e-07,9.999996e-01,-3.969044e-07,9.999996e-01,-3.969044e-07,-3.969044e-07,9.999996e-01,-3.969044e-07,-3.969044e-07,...,-3.969044e-07,-3.969044e-07,-3.969044e-07,9.999996e-01,-3.969044e-07,-3.969044e-07,2.584962e+00,-3.969044e-07,-3.969044e-07,-3.969044e-07
TNF,-6.300071e-09,-6.300071e-09,-6.300071e-09,-6.300071e-09,-6.300071e-09,-6.300071e-09,-6.300071e-09,-6.300071e-09,-6.300071e-09,-6.300071e-09,...,-6.300071e-09,-6.300071e-09,-6.300071e-09,-6.300071e-09,-6.300071e-09,-6.300071e-09,-6.300071e-09,-6.300071e-09,-6.300071e-09,-6.300071e-09
EGFR,9.999990e-01,-1.042661e-06,1.584961e+00,-1.042661e-06,4.247926e+00,2.999999e+00,-1.042661e-06,-1.042661e-06,9.999990e-01,-1.042661e-06,...,-1.042661e-06,1.999999e+00,-1.042661e-06,9.999990e-01,1.584961e+00,-1.042661e-06,2.807354e+00,9.999990e-01,-1.042661e-06,-1.042661e-06
NFKB1,-7.182079e-07,9.999993e-01,9.999993e-01,-7.182079e-07,9.999993e-01,2.321927e+00,-7.182079e-07,-7.182079e-07,-7.182079e-07,9.999993e-01,...,9.999993e-01,9.999993e-01,1.584962e+00,-7.182079e-07,-7.182079e-07,-7.182079e-07,9.999993e-01,-7.182079e-07,9.999993e-01,-7.182079e-07
FCN1,-6.300071e-09,-6.300071e-09,-6.300071e-09,-6.300071e-09,-6.300071e-09,-6.300071e-09,-6.300071e-09,-6.300071e-09,-6.300071e-09,-6.300071e-09,...,-6.300071e-09,-6.300071e-09,-6.300071e-09,-6.300071e-09,-6.300071e-09,-6.300071e-09,-6.300071e-09,-6.300071e-09,-6.300071e-09,-6.300071e-09

## All samples and cell types

In [27]:
all_cells.groupby(['celltype','sample_new', 'sample']).count()

                                ID  group  disease  hasnCoV  cluster  barcode
celltype sample_new sample
B        HC1        C51         15     15       15       15       15       15
         HC2        C52          5      5        5        5        5        5
         HC3        C100         9      9        9        9        9        9
         HC4        GSM3660650  22     22       22       22       22       22
         M1         C141        35     35       35       35       35       35
...                             ..    ...      ...      ...      ...      ...
pDC      M3         C144         3      3        3        3        3        3
         S1         C145        42     42       42       42       42       42
         S2         C143        32     32       32       32       32       32
         S4         C148         1      1        1        1        1        1
         S6         C152         1      1        1        1        1        1

[119 rows x 6 columns]

## Extract samples for each celltype

In [63]:
raw[patient].head()

,AAACCTGAGACACTAA-1,AAACCTGAGGAGTACC-1,AAACCTGAGGATATAC-1,AAACCTGAGGTCATCT-1,AAACCTGCACGGATAG-1,AAACCTGCACGGCTAC-1,AAACCTGCAGGGAGAG-1,AAACCTGCATGCATGT-1,AAACCTGGTCTAAACC-1,AAACCTGGTGCACCAC-1,...,TTTGTCACATCCGTGG-1,TTTGTCACATGACATC-1,TTTGTCAGTATTCTCT-1,TTTGTCAGTCGAACAG-1,TTTGTCAGTCGGATCC-1,TTTGTCAGTTAAAGTG-1,TTTGTCAGTTCCACGG-1,TTTGTCATCGCTGATA-1,TTTGTCATCGGAAACG-1,TTTGTCATCTTTACGT-1
MIR1302-2HG,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
FAM138A,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
OR4F5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
AL627309.1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
AL627309.3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [28]:
import GEOparse

def get_celltype_barcodes_of_patient( patient, celltypes, raw, all_cells, patient_to_sample, raw_barcodes ):
    celltype_barcodes = dict()
    celltypes_of_patient = dict()
    for celltype in celltypes:
        celltype_barcodes[celltype] =  get_celltype_barcodes_from_patient( patient, raw, celltype, all_cells)
        if len(celltype_barcodes[celltype] & raw_barcodes[patient]) != len(celltype_barcodes[celltype,patient]):
            print('{} ({}) \traw barcodes: {}\t{} metadata barcodes: {}\t intersection: {}'.format(
                patient, patient_to_sample[patient],
                len(raw_barcodes[patient]),
                celltype,
                len(celltype_barcodes[celltype,patient]),
                len(raw_barcodes[patient] & celltype_barcodes[celltype,patient])))
    return celltype_barcodes

In [29]:
h2_celltype_barcodes = get_celltype_barcodes_of_patient('HC2', celltypes, raw, all_cells, patient_to_sample, raw_barcodes)
h2_celltype_barcodes

KeyError: ('NK', 'HC2')

In [ ]:
import GEOparse
geo = dict()
raw = dict()
raw_barcodes = dict()
metadata_barcodes = dict()
epithelial_barcodes = dict()
sample_to_patient = dict(all_cells.groupby(['sample','sample_new']).count().index.tolist())
for gsm_file in balf_files:
    gsm_id, sample = gsm_file.split('_')[0:2]
    patient = sample_to_patient[sample]
    geo[patient] = GEOparse.get_GEO(geo=gsm_id, destdir=balf_dir)
    raw[patient] = get_matrix_from_h5(os.path.join(balf_dir,gsm_file))
    metadata_barcodes[patient] = set(all_cells[all_cells['sample_new'] == patient]['ID']
                                    .str.split('_').str.get(0)
                                    .values.tolist())
    raw_barcodes[patient] = set([raw_barcode.split('-')[0] for raw_barcode in raw[patient].columns])
    print('{} ({})\traw barcodes: {}\tepithelial metadata barcodes: {}\t intersection: {}'.format(
                 patient, sample,
                len(raw_barcodes[patient]), 
                len(metadata_barcodes[patient]), 
                len(raw_barcodes[patient] & metadata_barcodes[patient])))
    epithelial_barcodes[patient] = set(all_cells[(all_cells['sample_new'] == patient) &
                                               (all_cells['celltype'] == 'Epithelial')]['ID']
                                    .str.split('_').str.get(0)
                                    .values.tolist())
    print('{} ({}) \traw barcodes: {}\tepithelial metadata barcodes: {}\t intersection: {}'.format(
                patient, sample,
                len(raw_barcodes[patient]),
                len(epithelial_barcodes[patient]),
                len(raw_barcodes[patient] & epithelial_barcodes[patient])))

# Healthy control 4 (HC4)

In [23]:
hc4_cells = all_cells[(all_cells['sample_new'] == 'HC4')]
hc4_cells.head()

,ID,sample,sample_new,group,disease,hasnCoV,cluster,celltype,barcode
19173,AAACCTGCAGCATGAG_4,GSM3660650,HC4,HC,N,N,6,T,AAACCTGCAGCATGAG
19174,AAACCTGGTATATGGA_4,GSM3660650,HC4,HC,N,N,13,Epithelial,AAACCTGGTATATGGA
19175,AAACCTGGTTGTACAC_4,GSM3660650,HC4,HC,N,N,25,Epithelial,AAACCTGGTTGTACAC
19176,AAACCTGTCAGAGGTG_4,GSM3660650,HC4,HC,N,N,16,Epithelial,AAACCTGTCAGAGGTG
19177,AAACCTGTCGACAGCC_4,GSM3660650,HC4,HC,N,N,16,Epithelial,AAACCTGTCGACAGCC

In [24]:
hc4_cells.groupby('celltype').count()

,ID,sample,sample_new,group,disease,hasnCoV,cluster,barcode
celltype,,,,,,,,
B,22,22,22,22,22,22,22,22
Epithelial,1383,1383,1383,1383,1383,1383,1383,1383
Macrophages,683,683,683,683,683,683,683,683
Mast,19,19,19,19,19,19,19,19
NK,29,29,29,29,29,29,29,29
T,533,533,533,533,533,533,533,533
mDC,37,37,37,37,37,37,37,37
pDC,4,4,4,4,4,4,4,4

## Parse Healthy control 4 (HC4) GEO Sample

In [25]:
import GEOparse

HC4_geo_id = "GSM3660650"
HC4_geo_sample = GEOparse.get_GEO(geo=HC4_geo_id, destdir=balf_dir)

for key, value in HC4_geo_sample.metadata.items():
        print(" - %s : %s" % (key, ", ".join(value)))
print ("Table data:",)
print (HC4_geo_sample.table.head())

05-Jun-2020 15:27:49 DEBUG utils - Directory ../../MARS-Pathogenesis/Coronavirus/SARS-CoV-2/COVID-BALF/ already exists. Skipping.
05-Jun-2020 15:27:49 INFO GEOparse - File already exist: using local version.
05-Jun-2020 15:27:49 INFO GEOparse - Parsing ../../MARS-Pathogenesis/Coronavirus/SARS-CoV-2/COVID-BALF/GSM3660650.txt:

 - title : SC249NORbal_fresh
 - geo_accession : GSM3660650
 - status : Public on Jun 21 2019
 - submission_date : Mar 07 2019
 - last_update_date : Jun 23 2019
 - type : SRA
 - channel_count : 1
 - source_name_ch1 : fresh Brochoalvelolar lavage (BAL) + brush cells from healthy donor
 - organism_ch1 : Homo sapiens
 - taxid_ch1 : 9606
 - characteristics_ch1 : subject status: normal/healthy donor, tissue: lung, lung section/portion: fresh Brochoalvelolar lavage (BAL) + brush cells
 - molecule_ch1 : polyA RNA
 - extract_protocol_ch1 : 10X Genomics 3 Prime V2 chemistry, Explanted lungs were finely diced and digested for 1 hour in a mix of collagenase A/DNAse I.  A single cell suspension was generated by filtering lungs through 70 micron filters and resuspending cells in PBS containing 0.04% BSA.  Cells were loaded into the 10X Genomics Chromium instrument per manufacturer's directions., Libraries were constructed according to 10X Genomics' Single Cell 3’ Reagent Kits v2 User Guide
 - data_processing : 10X Genomics' Cell Ranger 2.0 software's mkfastq command was used for basecalling.  It is a wrapper for Illumina's bcl2fastq, Sequenced reads were then mapped to GRCh38 whole genome using 10X Genomics' Cell Ranger 2.0 software's cellranger count function, Cell Ranger output of raw_gene_bc_matrices were utilized for further downstream analysis in R with the package Seurat 2.3.4, only cells expressing at least 200 genes were kept for downstream analysis.  Further filtration removed cells expressing greater than 50,000 UMI or 35% mitochondrial genes., Genome_build: GRCh38, Supplementary_files_format_and_content: tsv files contain lists of genes and barcodes for each sample, mtx files count gene UMI couns for each sample
 - platform_id : GPL18573
 - contact_name : Tracy,,Tabib
 - contact_laboratory : Laboratory of Robert Lafyatis
 - contact_department : Department of Medicine
 - contact_institute : University of Pittsburgh
 - contact_address : 200 Lothrop Street
 - contact_city : Pittsburgh
 - contact_state : PA
 - contact_zip/postal_code : 15213
 - contact_country : USA
 - instrument_model : Illumina NextSeq 500
 - library_selection : cDNA
 - library_source : transcriptomic
 - library_strategy : RNA-Seq
 - relation : BioSample: https://www.ncbi.nlm.nih.gov/biosample/SAMN11086899
 - supplementary_file_1 : ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM3660nnn/GSM3660650/suppl/GSM3660650_SC249NORbal_fresh_barcodes.tsv.gz
 - supplementary_file_2 : ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM3660nnn/GSM3660650/suppl/GSM3660650_SC249NORbal_fresh_genes.tsv.gz
 - supplementary_file_3 : ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM3660nnn/GSM3660650/suppl/GSM3660650_SC249NORbal_fresh_matrix.mtx.gz
 - series_id : GSE128033
 - data_row_count : 0
Table data:
Empty DataFrame
Columns: []
Index: []

In [210]:
#print(hc4_raw.iloc[:10,:10].to_html())
hc4_raw.iloc[:10,:10]

barcode,AAACCTGAGAAACCAT-1,AAACCTGAGAAACCGC-1,AAACCTGAGAAACCTA-1,AAACCTGAGAAACGAG-1,AAACCTGAGAAACGCC-1,AAACCTGAGAAAGTGG-1,AAACCTGAGAACAACT-1,AAACCTGAGAACAATC-1,AAACCTGAGAACTCGG-1,AAACCTGAGAACTGTA-1
gene_name,,,,,,,,,,
MIR1302-2HG,0,0,0,0,0,0,0,0,0,0
FAM138A,0,0,0,0,0,0,0,0,0,0
OR4F5,0,0,0,0,0,0,0,0,0,0
AL627309.1,0,0,0,0,0,0,0,0,0,0
AL627309.3,0,0,0,0,0,0,0,0,0,0
AL627309.2,0,0,0,0,0,0,0,0,0,0
AL627309.4,0,0,0,0,0,0,0,0,0,0
AL732372.1,0,0,0,0,0,0,0,0,0,0
OR4F29,0,0,0,0,0,0,0,0,0,0
AC114498.1,0,0,0,0,0,0,0,0,0,0

# Macrophage

In [9]:
macrophage = all_cells[all_cells['celltype']== 'Macrophages']
macrophage.head()

,ID,sample,sample_new,group,disease,hasnCoV,cluster,celltype,barcode
0,AAACCTGAGACACTAA_1,C51,HC1,HC,N,N,3,Macrophages,AAACCTGAGACACTAA
1,AAACCTGAGGAGTACC_1,C51,HC1,HC,N,N,3,Macrophages,AAACCTGAGGAGTACC
2,AAACCTGAGGATATAC_1,C51,HC1,HC,N,N,3,Macrophages,AAACCTGAGGATATAC
3,AAACCTGAGGTCATCT_1,C51,HC1,HC,N,N,3,Macrophages,AAACCTGAGGTCATCT
4,AAACCTGCACGGATAG_1,C51,HC1,HC,N,N,5,Macrophages,AAACCTGCACGGATAG

2710

## Epithelial cells

In [30]:
epithelial = all_cells[all_cells['celltype'] == 'Epithelial']
epithelial.head()

,ID,sample,sample_new,group,disease,hasnCoV,cluster,celltype,barcode
1070,AGATTGCAGATAGCAT_1,C51,HC1,HC,N,N,16,Epithelial,AGATTGCAGATAGCAT
1313,AGGGAGTGTTGATTGC_1,C51,HC1,HC,N,N,16,Epithelial,AGGGAGTGTTGATTGC
1445,AGTGGGACACCAGATT_1,C51,HC1,HC,N,N,16,Epithelial,AGTGGGACACCAGATT
1799,ATTACTCTCGGAAATA_1,C51,HC1,HC,N,N,16,Epithelial,ATTACTCTCGGAAATA
2729,CCATGTCCATCCGCGA_1,C51,HC1,HC,N,N,16,Epithelial,CCATGTCCATCCGCGA

In [110]:
epithelial[epithelial['sample'] == 'C141']

,ID,sample,sample_new,group,disease,hasnCoV,cluster,celltype,barcode
21908,AAAGCAAAGTGAAGAG_5,C141,M1,M,Y,N,16,Epithelial,AAAGCAAAGTGAAGAG
22026,AAGGAGCTCTAAGCCA_5,C141,M1,M,Y,N,16,Epithelial,AAGGAGCTCTAAGCCA
22071,ACACCCTAGTTACCCA_5,C141,M1,M,Y,N,13,Epithelial,ACACCCTAGTTACCCA
22129,ACCAGTAAGTTTCCTT_5,C141,M1,M,Y,N,16,Epithelial,ACCAGTAAGTTTCCTT
22173,ACGAGGATCAACCAAC_5,C141,M1,M,Y,N,16,Epithelial,ACGAGGATCAACCAAC
...,...,...,...,...,...,...,...,...,...
25138,TGCTACCCAACCGCCA_5,C141,M1,M,Y,N,16,Epithelial,TGCTACCCAACCGCCA
25152,TGGACGCAGGGATACC_5,C141,M1,M,Y,N,16,Epithelial,TGGACGCAGGGATACC
25222,TGTCCCATCCGCGCAA_5,C141,M1,M,Y,N,16,Epithelial,TGTCCCATCCGCGCAA
25330,TTCTCCTTCCCTAACC_5,C141,M1,M,Y,N,25,Epithelial,TTCTCCTTCCCTAACC
25383,TTTACTGAGATGGGTC_5,C141,M1,M,Y,N,13,Epithelial,TTTACTGAGATGGGTC

### Severe COVID-19 patient 2 (S2) Epithelial cell barcodes

In [111]:
S2_epi = set(epithelial.loc[epithelial['sample_new'] == 'S2']['barcode'].values.tolist())
len(S2_epi)

309

### Healthy control 4 (HC4) Epithelial cell barcodes

In [112]:
HC4_epi = set(epithelial.loc[epithelial['sample_new']=='HC4']['barcode'].values.tolist())
len(HC4_epi)

1383

In [113]:
epithelial.groupby(['sample','sample_new']).count()

,,ID,group,disease,hasnCoV,cluster,celltype,barcode
sample,sample_new,,,,,,,
C100,HC3,13,13,13,13,13,13,13
C141,M1,83,83,83,83,83,83,83
C142,M2,94,94,94,94,94,94,94
C143,S2,309,309,309,309,309,309,309
C144,M3,38,38,38,38,38,38,38
C145,S1,368,368,368,368,368,368,368
C146,S3,312,312,312,312,312,312,312
C148,S4,373,373,373,373,373,373,373
C149,S5,185,185,185,185,185,185,185
C152,S6,327,327,327,327,327,327,327
C51,HC1,13,13,13,13,13,13,13
C52,HC2,33,33,33,33,33,33,33
GSM3660650,HC4,1383,1383,1383,1383,1383,1383,1383

In [184]:
epithelial.groupby(['sample','sample_new']).count().index.tolist()

[('C100', 'HC3'),
 ('C141', 'M1'),
 ('C142', 'M2'),
 ('C143', 'S2'),
 ('C144', 'M3'),
 ('C145', 'S1'),
 ('C146', 'S3'),
 ('C148', 'S4'),
 ('C149', 'S5'),
 ('C152', 'S6'),
 ('C51', 'HC1'),
 ('C52', 'HC2'),
 ('GSM3660650', 'HC4')]

In [114]:
epithelial.groupby('group').count()

         ID  sample  sample_new  disease  hasnCoV  cluster  celltype  barcode
group
HC     1442    1442        1442     1442     1442     1442      1442     1442
M       215     215         215      215      215      215       215      215
S      1874    1874        1874     1874     1874     1874      1874     1874

In [3]:
epithelial.groupby('sample_new').count()

              ID  sample  group  disease  hasnCoV  cluster  celltype
sample_new
HC1           13      13     13       13       13       13        13
HC2           33      33     33       33       33       33        33
HC3           13      13     13       13       13       13        13
HC4         1383    1383   1383     1383     1383     1383      1383
M1            83      83     83       83       83       83        83
M2            94      94     94       94       94       94        94
M3            38      38     38       38       38       38        38
S1           368     368    368      368      368      368       368
S2           309     309    309      309      309      309       309
S3           312     312    312      312      312      312       312
S4           373     373    373      373      373      373       373
S5           185     185    185      185      185      185       185
S6           327     327    327      327      327      327       327

In [117]:
epi_cluster_groups =  {'13' : 'Epithelial',
           '16' : 'Epithelial',
           '25' : 'Epithelial',
           '28' : 'Epithelial',
           '31' : 'Epithelial'}
epi_cluster_groups

{'13': 'Epithelial',
 '16': 'Epithelial',
 '25': 'Epithelial',
 '28': 'Epithelial',
 '31': 'Epithelial'}

## Compare Raw HC4 barcodes with Metdata HC4 barcodes

In [211]:
hc4_metadata_barcodes = set(hc4_cells['ID'].str.split('_').str.get(0).values.tolist())
hc4_raw_barcodes = set([raw.split('-')[0] for raw in hc4_raw.columns])
len(hc4_raw_barcodes), len(hc4_metadata_barcodes), len(hc4_raw_barcodes & hc4_metadata_barcodes)

(737280, 2710, 2710)

# Number of Epithelial cells in H4

In [212]:
hc4_epithelial_cells = hc4_cells[hc4_cells['celltype'] == 'Epithelial']
hc4_epithelial_metadata_barcodes = set(hc4_epithelial_cells['ID'].str.split('_').str.get(0).values.tolist())
len(hc4_epithelial_metadata_barcodes), len(hc4_raw_barcodes & hc4_epithelial_metadata_barcodes)

(1383, 1383)

## Write out Healthy Control 4 epithelial cells to csv

In [213]:
old_hc4_raw_columns = [b for b in hc4_raw.columns]
hc4_raw.columns = [barcode.split('-')[0] for barcode in hc4_raw.columns]
hc4_raw[hc4_epithelial_metadata_barcodes].to_csv(
    os.path.join(balf_dir, 'Epithelial','hc4_umi_epithelial.csv'))
hc4_raw.columns = old_hc4_raw_columns

# Severe COVID-19 patient 2

In [124]:
s2_cells = all_cells[(all_cells['sample_new'] == 'S2')]

s2_cells.head()

,ID,sample,sample_new,group,disease,hasnCoV,cluster,celltype,barcode
29194,AAACCTGAGACTTTCG_8,C143,S2,S,Y,N,4,Macrophages,AAACCTGAGACTTTCG
29195,AAACCTGAGCATGGCA_8,C143,S2,S,Y,N,0,Macrophages,AAACCTGAGCATGGCA
29196,AAACCTGAGCCATCGC_8,C143,S2,S,Y,N,3,Macrophages,AAACCTGAGCCATCGC
29197,AAACCTGAGCGTGAAC_8,C143,S2,S,Y,N,15,Neutrophil,AAACCTGAGCGTGAAC
29198,AAACCTGAGGACATTA_8,C143,S2,S,Y,N,5,Macrophages,AAACCTGAGGACATTA

## Parse Severe COVID-19 patient 2 (S2) GEO sample file

In [139]:
S2_sample_id = 'C144'
S2_geo_id = 'GSM4339772'
S2_raw_file = balf_files[3]

In [135]:
S2_geo_sample = GEOparse.get_GEO(geo=S2_geo_id, destdir=balf_dir)

for key, value in S2_geo_sample.metadata.items():
        print(" - %s : %s" % (key, ", ".join(value)))
print ("Table data:",)
print (S2_geo_sample.table.head())

28-May-2020 10:48:47 DEBUG utils - Directory ../../MARS-Pathogenesis/Coronavirus/SARS-CoV-2/COVID-BALF/ already exists. Skipping.
28-May-2020 10:48:47 INFO GEOparse - Downloading http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?targ=self&acc=GSM4339772&form=text&view=full to ../../MARS-Pathogenesis/Coronavirus/SARS-CoV-2/COVID-BALF/GSM4339772.txt
28-May-2020 10:48:48 DEBUG downloader - Total size: 0
28-May-2020 10:48:48 DEBUG downloader - md5: None
3.92kB [00:00, 1.58MB/s]
28-May-2020 10:48:48 DEBUG downloader - Moving /var/folders/z1/nhct2gps3y94tkbwqvvd7y_jw6p1l8/T/tmpfvirto9h to /Users/zuck016/Projects/Proposals/MARS/Pathogenesis/MARS-Pathogenesis/Coronavirus/SARS-CoV-2/COVID-BALF/GSM4339772.txt
28-May-2020 10:48:48 DEBUG downloader - Successfully downloaded http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?targ=self&acc=GSM4339772&form=text&view=full
28-May-2020 10:48:48 INFO GEOparse - Parsing ../../MARS-Pathogenesis/Coronavirus/SARS-CoV-2/COVID-BALF/GSM4339772.txt:

 - title : BALF, C144 (scRNA-seq)
 - geo_accession : GSM4339772
 - status : Public on Apr 22 2020
 - submission_date : Feb 25 2020
 - last_update_date : Apr 22 2020
 - type : SRA
 - channel_count : 1
 - source_name_ch1 : BALF
 - organism_ch1 : Homo sapiens
 - taxid_ch1 : 9606
 - characteristics_ch1 : disease state: Coronavirus infected disease-19 (COVID-19), patient group: mild, tissue: lung, sample type: BALF, cell subsets: Total cell
 - molecule_ch1 : polyA RNA
 - extract_protocol_ch1 : Total 11 µl of single cell suspension and 40 µl barcoded Gel Beads were loaded to Chromium Chip A to generate single-cell gel bead-in-emulsion (GEM). The poly-adenylated transcripts were reverse-transcribed later. The single-cell capturing and downstream library constructions were performed using the Chromium Single Cell 5’ library preparation kit according to the manufacturer’s protocol (10x Genomics). Full-length cDNA along with cell-barcode identifiers were PCR-amplified and sequencing libraries were prepared and normalized to 3 nM.
 - description : Single-cell RNAseq data
 - data_processing : The Cell Ranger Software Suite (Version 3.1.0) was used to perform sample de-multiplexing, barcode processing and single-cell 5’ UMI counting with human GRCh38 as the reference genome. Specifically, splicing-aware aligner STAR was used in FASTQs alignment. Cell barcodes were then determined based on distribution of UMI count automatically. Finally, gene-barcode matrix of all 6 donors and 8 previously reported healthy control was integrated with Seurat v3 to remove batch effect across different donors. Following criteria were then applied to each cell, i.e., gene number between 200 and 6000, UMI count above 1000 and mitochondrial gene percentage below 0.1., The filtered gene-barcode matrix was normalized with LogNormalize methods in Seurat and analyzed by principal component analysis (PCA) using the top 2, 000 most variable genes. Then Uniform Manifold Approximation and Projection (UMAP) was performed on the top 50 principal components for visualizing the cells. Meanwhile, graph-based clustering was performed on the PCA-reduced data for clustering analysis with Seurat v3., MAST in Seurat v3 was used to perform differential analysis. For each cluster, differentially-expressed genes (DEGs) were generated relative to all of the other cells., The TCR sequences for each single T cell were assembled by Cell Ranger vdj pipeline (v3.1.0), leading to the identification of CDR3 sequence and the rearranged TCR gene. Cells with both TCR alpha and beta chains were kept and cells with only one TCR chain were discarded., Genome_build: GRCh38 + COVID(MN908947), Supplementary_files_format_and_content: h5, raw count matrix generated by Cell Ranger count; csv, tcr contig annotations generated by Cell Ranger vdj
 - platform_id : GPL23227
 - contact_name : Zheng,,Zhang
 - contact_institute : Shenzhen 3rd People's Hospital
 - contact_address : No. 29, Bulan Road
 - contact_city : Shenzhen
 - contact_state : Guangdong
 - contact_zip/postal_code : 454171
 - contact_country : China
 - instrument_model : BGISEQ-500
 - library_selection : cDNA
 - library_source : transcriptomic
 - library_strategy : RNA-Seq
 - relation : BioSample: https://www.ncbi.nlm.nih.gov/biosample/SAMN14207958, SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX7802549
 - supplementary_file_1 : ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM4339nnn/GSM4339772/suppl/GSM4339772_C144_filtered_feature_bc_matrix.h5
 - series_id : GSE145926
 - data_row_count : 0
Table data:
Empty DataFrame
Columns: []
Index: []

## Parse S2 raw HDF5 file

In [141]:
s2_raw = get_matrix_from_h5(os.path.join(balf_dir,S2_raw_file))
#print(s2_raw.iloc[:10,:10].to_html())
s2_raw.iloc[:10,:10]

<class 'str'> genome

,AAACCTGAGCTAGTGG,AAACCTGCAGCCTTTC,AAACCTGCAGCTGTGC,AAACCTGGTCTAGTGT,AAACCTGGTGACTCAT,AAACCTGTCGTCCGTT,AAACGGGAGACGCTTT,AAACGGGAGATCGGGT,AAACGGGAGCGTCTAT,AAACGGGCAATCGAAA
MIR1302-2HG,0,0,0,0,0,0,0,0,0,0
FAM138A,0,0,0,0,0,0,0,0,0,0
OR4F5,0,0,0,0,0,0,0,0,0,0
AL627309.1,0,0,0,0,0,0,0,0,0,0
AL627309.3,0,0,0,0,0,0,0,0,0,0
AL627309.2,0,0,0,0,0,0,0,0,0,0
AL627309.4,0,0,0,0,0,0,0,0,0,0
AL732372.1,0,0,0,0,0,0,0,0,0,0
OR4F29,0,0,0,0,0,0,0,0,0,0
AC114498.1,0,0,0,0,0,0,0,0,0,0

In [143]:
s2_raw.shape

(33539, 3716)

## Compare Raw S2 barcodes with S2 metadata barcodes

In [159]:
s2_metadata_barcodes = set(s2_cells['ID'].str.split('_').str.get(0).values.tolist())
s2_raw_barcodes = set([raw.split('-')[0] for raw in s2_raw.columns])
len(s2_raw_barcodes), len(s2_metadata_barcodes)

(3716, 16883)

In [160]:
len(set(s2_raw_barcodes) & set(s2_metadata_barcodes))

96

In [164]:
s2_epithelial_cells = s2_cells[s2_cells['celltype'] == 'Epithelial']
s2_epithelial_metadata_barcodes = set(s2_epithelial_cells['ID'].str.split('_').str.get(0).values.tolist())
len(s2_epithelial_metadata_barcodes), len(s2_raw_barcodes & s2_epithelial_metadata_barcodes)

(309, 4)

## Healthy controls

In [193]:
healthy_controls = all_cells[(all_cells['group'] == 'HC') & (all_cells['celltype'] == 'Epithelial')].groupby(['sample', 'sample_new']).count()
healthy_controls

,,ID,group,disease,hasnCoV,cluster,celltype,barcode
sample,sample_new,,,,,,,
C100,HC3,13,13,13,13,13,13,13
C51,HC1,13,13,13,13,13,13,13
C52,HC2,33,33,33,33,33,33,33
GSM3660650,HC4,1383,1383,1383,1383,1383,1383,1383

In [41]:
patients = all_cells.groupby('sample_new').count().index.tolist()
patients_no_HC4 = [p for p in patients if p != 'HC4']

## Write out epithelial samples to csv

In [215]:
for patient in patients_no_HC4:
    raw[patient].columns = [barcode.split('-')[0] for barcode in raw[patient].columns]
    #raw[patient].to_csv(os.path.join(
    #    balf_dir,
    #    '{}_umi_full.csv'.format(patient)))
    #raw[patient][metadata_barcodes[patient]].to_csv(
    #    os.path.join(balf_dir, 'Annotated',
    #                 '{}_umi_annotated.csv'.format(patient)))
    raw[patient][epithelial_barcodes[patient]].to_csv(
        os.path.join(balf_dir, 'Epithelial',
                    '{}_umi_epithelial.csv'.format(patient)))

In [52]:
tmgpp = {}
for patient in patients_no_HC4:
    tmgpp[patient] = raw[patient].loc[model_genes].sum(axis=1)
tmgpp['HC4'] = hc4_raw.loc[model_genes].sum(axis=1)
total_model_genes_per_patient = pd.DataFrame(tmgpp)

In [54]:

total_model_genes_per_patient[sorted(total_model_genes_per_patient.columns)]

,HC1,HC2,HC3,HC4,M1,M2,M3,S1,S2,S3,S4,S5,S6
gene_name,,,,,,,,,,,,,
IL6,41,7,57,89.0,2783,1293,18,2773,3530,101,677,851,115
STAT3,3914,1739,10790,2772.0,9554,8607,786,8478,25927,1995,4044,2663,4275
ACE2,2,0,1,45.0,56,24,12,45,59,21,305,138,35
ADAM17,11892,4586,21162,880.0,12249,10612,2172,11119,25206,1763,4799,1691,3566
AGTR1,0,0,0,3.0,1,0,0,0,0,0,0,0,0
EGF,0,0,1,5.0,6,17,86,34,28,3,37,5,8
IL6R,1268,920,2838,379.0,7255,7394,522,8649,25538,1897,3561,910,3554